name:                hssh
version:             0.1.0.0
github:              lpeterse/haskell-ssh
license:             MIT
author:              Lars Petersen
maintainer:          info@lars-petersen.net
copyright:           2017 Lars Petersen
category:            Network

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            SSH protocol implementation
description:         Please see the README on Github at <https://github.com/lpeterse/haskell-ssh#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- cereal
- containers
- cryptonite
- memory
- stm
- filepath
- directory
- data-default
- socket >= 0.8.2.0
- socket-unix

default-extensions:
- LambdaCase
- BlockArguments
- OverloadedStrings
- GeneralizedNewtypeDeriving

library:
  source-dirs: src/hssh
  ghc-options: -Wall -fno-warn-orphans
  exposed-modules:
    - Network.SSH
    - Network.SSH.Client
    - Network.SSH.Server
  dependencies:
    - hssh-internal

internal-libraries:
  hssh-internal:
    source-dirs: src/hssh-internal
    ghc-options: -Wall -fno-warn-orphans
    exposed-modules:
      - Network.SSH.Agent
      - Network.SSH.Algorithms
      - Network.SSH.Client.Client
      - Network.SSH.Client.Connection
      - Network.SSH.Client.HostKeyVerifier
      - Network.SSH.Client.UserAuth
      - Network.SSH.Duration
      - Network.SSH.Address
      - Network.SSH.Server.Connection
      - Network.SSH.Server.UserAuth
      - Network.SSH.Server.Server
      - Network.SSH.Server.Switchboard
      - Network.SSH.Encoding
      - Network.SSH.Environment
      - Network.SSH.Exception
      - Network.SSH.Key
      - Network.SSH.Message
      - Network.SSH.Name
      - Network.SSH.Stream
      - Network.SSH.TermInfo
      - Network.SSH.Transport
      - Network.SSH.TWindowBuffer

tests:
  hssh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssh-internal
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
